import os
import json
import re
from jinja2 import Environment, FileSystemLoader


def load_characterization_data():
    """Load characterization data generated by the analog solver pipeline."""
    data_path = os.path.join(
        os.path.dirname(os.path.abspath(__file__)),
        "..", "..", "generated", "json", "characterization_data.json",
    )
    if os.path.exists(data_path):
        with open(data_path, "r") as f:
            return json.load(f)
    else:
        print(f"[WARNING] {data_path} not found. Ensure pipeline.py has been run.")
        raise FileNotFoundError(f"characterization_data.json not found at {data_path}")


def main():
    base_dir = os.path.dirname(os.path.abspath(__file__))
    templates_dir = os.path.join(base_dir, "templates")
    out_dir = os.path.join(os.path.dirname(base_dir), "..", "uvm_verification")

    if not os.path.exists(out_dir):
        os.makedirs(out_dir)

    # Initialize Jinja2 environment
    env = Environment(loader=FileSystemLoader(templates_dir))

    # Load characterization data
    data = load_characterization_data()
    print(f"Loaded characterization data: f0={data['f_0']/1e9:.4f} GHz, "
          f"V_pp={data.get('v_pp', 'N/A')} V, source={data.get('source', 'unknown')}")

    # Generate SVA Package
    sva_template = env.get_template("sva_package.sv.j2")
    sva_output = sva_template.render(
        source_json=data["source"],
        v_max=data["v_max"],
        v_min=data["v_min"],
        f_0=data["f_0"],
    )
    sva_path = os.path.join(out_dir, "vco_sva_pkg.sv")
    with open(sva_path, "w") as f:
        f.write(sva_output)
    print(f"Generated: {os.path.abspath(sva_path)}")

    # Generate UVM Sequence
    uvm_template = env.get_template("uvm_sequence.svh.j2")
    uvm_output = uvm_template.render(
        source_json=data["source"],
        gamma_rms=data["gamma_rms"],
        gamma_dc=data["gamma_dc"],
        f_0=data["f_0"],
        num_cycles=data["num_cycles"],
        v_tune_nom=data["v_tune_nom"],
    )
    uvm_path = os.path.join(out_dir, "vco_jitter_sequence.svh")
    with open(uvm_path, "w") as f:
        f.write(uvm_output)
    print(f"Generated: {os.path.abspath(uvm_path)}")

    # Align RNM DUT parameters with characterization data
    rnm_path = os.path.join(out_dir, "vco_rnm_dut.sv")
    if os.path.exists(rnm_path):
        with open(rnm_path, "r") as f:
            rnm_content = f.read()

        f0 = data["f_0"]
        v_pp = data.get("v_pp", data["v_max"] - data["v_min"])
        v_amplitude = v_pp / 2.0  # Half-swing: DUT uses (V_AMPLITUDE/2)*sin(phase)
        dc_offset = (data["v_max"] + data["v_min"]) / 2.0
        kvco = data.get("kvco_hz_per_v", 500e6)

        rnm_content = re.sub(
            r"localparam real F_0\s*=\s*[^;]+;",
            f"localparam real F_0 = {f0};  // {f0/1e9:.4f} GHz (from characterization)",
            rnm_content,
        )
        rnm_content = re.sub(
            r"localparam real K_VCO\s*=\s*[^;]+;",
            f"localparam real K_VCO = {kvco};  // {kvco/1e6:.0f} MHz/V",
            rnm_content,
        )
        rnm_content = re.sub(
            r"localparam real V_AMPLITUDE\s*=\s*[^;]+;",
            f"localparam real V_AMPLITUDE = {v_amplitude};  // {v_amplitude:.3f}V p-p",
            rnm_content,
        )

        # If DC_OFFSET constant exists, update it; otherwise it's computed in the always block
        if "DC_OFFSET" in rnm_content:
            rnm_content = re.sub(
                r"localparam real DC_OFFSET\s*=\s*[^;]+;",
                f"localparam real DC_OFFSET = {dc_offset};",
                rnm_content,
            )

        with open(rnm_path, "w") as f:
            f.write(rnm_content)
        print(f"Aligned RNM DUT: F_0={f0/1e9:.4f} GHz, V_AMP={v_amplitude:.3f}V, "
              f"K_VCO={kvco/1e6:.0f} MHz/V -> {os.path.abspath(rnm_path)}")


if __name__ == "__main__":
    main()
