"""
siliconforge.cml_design
========================

CML Prescaler design for 10.25 GHz to 2.05 GHz frequency bridging.

Implements guidebook Chapter 6:
- SiGe HBT sizing for 10 GHz operation
- Common-centroid matching requirements
- Emitter follower buffers
"""

from __future__ import annotations

import math
from dataclasses import dataclass


@dataclass(frozen=True)
class CMLLatchParameters:
    """Parameters for one CML latch stage."""

    load_capacitance_f: float
    target_frequency_hz: float
    risetime_target_s: float
    r_load_ohm: float
    i_tail_ma: float
    v_swing_mv: float
    c_cpb_f: float  # Miller-multiplied capacitance


@dataclass(frozen=True)
class PrescalerParameters:
    """Complete prescaler design parameters."""

    n_division: int  # 5 for divide-by-5
    input_frequency_hz: float  # 10.25 GHz
    output_frequency_hz: float  # 2.05 GHz
    latch_params: CMLLatchParameters
    ef_slew_current_ma: float


def size_cml_latch(
    load_capacitance_f: float,
    target_frequency_hz: float,
    v_swing_mv: float = 300.0,
) -> CMLLatchParameters:
    """Size CML latch for target frequency and load.

    From guidebook Eq 6.3-6.4:
    - R_L = tau / C_load (Miller-multiplied gate capacitance included)
    - I_tail = V_swing / R_L

    Parameters
    ----------
    load_capacitance_f : float
        Total capacitance to drive (C_pi + C_wire)
    target_frequency_hz : float
        Clock frequency this latch must switch at
    v_swing_mv : float
        Target voltage swing (default 300 mV for adequate noise margin)

    Returns
    -------
    CMLLatchParameters
    """
    if load_capacitance_f <= 0:
        raise ValueError(
            f"load_capacitance_f must be > 0; got {load_capacitance_f}")
    if target_frequency_hz <= 0:
        raise ValueError(
            f"target_frequency_hz must be > 0; got {target_frequency_hz}")
    if v_swing_mv <= 0:
        raise ValueError(f"v_swing_mv must be > 0; got {v_swing_mv}")

    period = 1.0 / target_frequency_hz
    tau = period / 20.0  # Conservative

    r_load = tau / load_capacitance_f
    i_tail = (v_swing_mv / 1000.0) / r_load

    # Capacitance at cascode node (Miller effect)
    c_cpb = load_capacitance_f * 5.0  # Typical gain of 5 in CML

    return CMLLatchParameters(
        load_capacitance_f=load_capacitance_f,
        target_frequency_hz=target_frequency_hz,
        risetime_target_s=tau,
        r_load_ohm=r_load,
        i_tail_ma=i_tail * 1e3,
        v_swing_mv=v_swing_mv,
        c_cpb_f=c_cpb,
    )


def design_prescaler(
    input_frequency_hz: float = 10.25e9,
    n_division: int = 5,
    load_capacitance_f: float = 50e-15,
    v_swing_mv: float = 300.0,
) -> PrescalerParameters:
    """Design complete divide-by-N CML prescaler.

    From guidebook Section 6.3-6.4
    """
    if input_frequency_hz <= 0:
        raise ValueError(
            f"input_frequency_hz must be > 0; got {input_frequency_hz}")
    if n_division < 1:
        raise ValueError(f"n_division must be >= 1; got {n_division}")

    output_frequency = input_frequency_hz / n_division

    latch = size_cml_latch(
        load_capacitance_f=load_capacitance_f,
        target_frequency_hz=input_frequency_hz,
        v_swing_mv=v_swing_mv,
    )

    ef_current = size_emitter_follower(
        load_capacitance_f=load_capacitance_f,
        risetime_target_s=latch.risetime_target_s,
    )

    return PrescalerParameters(
        n_division=n_division,
        input_frequency_hz=input_frequency_hz,
        output_frequency_hz=output_frequency,
        latch_params=latch,
        ef_slew_current_ma=ef_current * 1e3,
    )


def generate_prescaler_testbench(params: PrescalerParameters) -> str:
    """Generate SPICE testbench for CML prescaler."""
    lines = [
        "* CML Prescaler Testbench",
        f"* Input frequency: {params.input_frequency_hz/1e9:.2f} GHz",
        f"* Division: /{params.n_division}",
        "",
        "VDD VDD 0 DC 1.2",
        "VSS VSS 0 DC 0",
        "",
        f"XI1 CLK_IN VOUT VSS VDD prescaler_core",
        f".TRAN 0 10n",
        f".PARAM freq = {params.output_frequency_hz/1e6:.2f}Meg",
        ".END",
    ]
    return "\n".join(lines)


def size_emitter_follower(
    load_capacitance_f: float,
    risetime_target_s: float,
) -> float:
    """Size emitter follower for level shifting.

    From guidebook Eq 6.5:
    I_EF = C_load * dV/dt

    Returns required tail current in Amps.
    """
    i_ef = load_capacitance_f * 0.3 / risetime_target_s
    return i_ef


def generate_cml_latch_netlist(params: CMLLatchParameters) -> str:
    """Generate SPICE netlist for CML latch using SG13G2 model names."""
    lines = [
        "* CML Latch - generated by siliconforge",
        f"* Target frequency: {params.target_frequency_hz/1e9:.2f} GHz",
        f"* Tail current: {params.i_tail_ma:.1f} mA, R_load: {params.r_load_ohm:.0f} ohm",
        "",
        ".include 'models/sg13g2_hbt.lib'",
        "",
        "***** TAIL CURRENT *****",
        f"IRF RSS VSS RVDD DC {params.i_tail_ma:.6g}",
        "",
        "***** LOAD RESISTORS *****",
        f"RRP OUTP VSS RES {params.r_load_ohm:.2f}",
        f"RRN OUTM VSS RES {params.r_load_ohm:.2f}",
        "",
        "***** HBT PAIR *****",
        f"Q1 OUTP CLK RVDD VSS sg13_hbt_npn w=20u l=0.13u",
        f"Q2 OUTM CLKN RVDD VSS sg13_hbt_pnp w=20u l=0.13u",
    ]
    return "\n".join(lines)


def generate_cml_divider_chain(
    n_total: int = 5,
    n_per_stage: int = 1,
) -> list[str]:
    """Generate list of stage dividers for multi-stage division.

    For divide-by-5: returns 5 single-divider netlists.
    """
    return [f"XDIV{i} IN{i} OUT{i} VSS VDD cml_latch" for i in range(n_total)]


if __name__ == "__main__":
    from pathlib import Path

    params = design_prescaler(input_frequency_hz=10.25e9, n_division=5)
    print(
        f"Prescaler: {params.input_frequency_hz/1e9:.2f}GHz -> {params.output_frequency_hz/1e9:.2f}GHz")
    print(f"Tail current: {params.latch_params.i_tail_ma:.2f} mA")

    netlist = generate_cml_latch_netlist(params.latch_params)
    Path("generated/rtl/cml_latch.cir").write_text(netlist)
    print("Generated cml_latch.cir")
