// ==============================================================================
// AUTOMATICALLY GENERATED FILE
// Generated by: OscillatorLab Verification Asset Generator
// Source: case_study: tests/case_study
// Description: Cycle-accurate SystemVerilog Assertions derived from Analog PSS
// ==============================================================================

package vco_sva_pkg;

    // Physical Limits Extracted from PSS Characterization
    localparam real V_MAX = 1.2;
    localparam real V_MIN = 0.38;
    localparam real F_0   = 10248776304.520353;

endpackage

// SVA Interface to bind to the RNM DUT
interface vco_sva_if (
    input logic clk,
    input logic rst_n,
    input real  v_out,
    input real  v_tune
);

    import vco_sva_pkg::*;

    // Startup blanking counter — suppress checks during oscillator startup
    integer startup_cnt = 0;
    logic startup_done = 0;

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            startup_cnt <= 0;
            startup_done <= 0;
        end else if (!startup_done) begin
            if (startup_cnt >= 10)
                startup_done <= 1;
            else
                startup_cnt <= startup_cnt + 1;
        end
    end

    // Property: Ensure output voltage never exceeds physical PSS bounds
    // Only checks after startup blanking period
    property p_vout_bounds;
        @(posedge clk) disable iff (!rst_n || !startup_done)
        (v_out >= V_MIN) && (v_out <= V_MAX);
    endproperty

    assert property (p_vout_bounds) 
    else $error("VCO Amplitude Violation! v_out=%f exceeded physical limits [%f, %f]", 
                v_out, V_MIN, V_MAX);

endinterface