// ==============================================================================
// AUTOMATICALLY GENERATED FILE
// Generated by: OscillatorLab Statistical Coverage Generator
// Source: Synthesized Analytical Dataset (MOCK) (N = 1000)
// Description: UVM Covergroup mapping mathematically proven 3-sigma variance
// ==============================================================================

`ifndef VCO_COVERAGE_SVH
`define VCO_COVERAGE_SVH

import uvm_pkg::*;
`include "uvm_macros.svh"

class vco_coverage extends uvm_subscriber #(real);
    `uvm_component_utils(vco_coverage)

    // Statistical Parameters Extracted from Monte Carlo
    // Mean (u): 1.000e+10
    // Std Dev (sigma): 2.405e+07

    longint current_f0_khz;

    covergroup cg_vco_statistical_variance;
        option.per_instance = 1;
        
        cp_f0_variance: coverpoint current_f0_khz {
            
            bins minus_3_sigma = {[9928683 : 9952735]};
            
            bins minus_2_sigma = {[9952735 : 9976786]};
            
            bins minus_1_sigma = {[9976786 : 10000837]};
            
            bins plus_1_sigma = {[10000837 : 10024889]};
            
            bins plus_2_sigma = {[10024889 : 10048940]};
            
            bins plus_3_sigma = {[10048940 : 10072991]};
            
        }
    endgroup

    function new(string name="vco_coverage", uvm_component parent=null);
        super.new(name, parent);
        cg_vco_statistical_variance = new();
    endfunction

    virtual function void write(real t);
        current_f0_khz = longint'(t / 1000.0);
        cg_vco_statistical_variance.sample();
    endfunction

endclass

`endif // VCO_COVERAGE_SVH