// ==============================================================================
// AUTOMATICALLY GENERATED FILE
// Generated by: OscillatorLab Verification Asset Generator
// Source: case_study: tests/case_study
// Description: UVM Sequence injecting physically accurate PPV-derived jitter
// ==============================================================================

`ifndef VCO_JITTER_SEQUENCE_SVH
`define VCO_JITTER_SEQUENCE_SVH

import uvm_pkg::*;
`include "uvm_macros.svh"

class vco_jitter_sequence extends uvm_sequence #(vco_transaction);
    `uvm_object_utils(vco_jitter_sequence)

    // PPV Extracted Phase Noise Metrics
    localparam real GAMMA_RMS = 0.04126790330305455;
    localparam real GAMMA_DC  = 0.0006835182213414462;
    localparam real F_0       = 10248776304.520353;

    function new(string name="vco_jitter_sequence");
        super.new(name);
    endfunction

    virtual task body();
        vco_transaction req;
        real dt_phase_deviation;

        `uvm_info("VCO_SEQ", $sformatf("Starting physically calibrated jitter sequence (Gamma_RMS: %e)", GAMMA_RMS), UVM_LOW)

        repeat (1000) begin
            req = vco_transaction::type_id::create("req");
            start_item(req);
            
            // Calculate random phase deviation using Gamma metrics
            // dt = Gamma_RMS * N(0,1) + Gamma_DC
            // Using a simple SystemVerilog approximation or DPI-C call
            // $dist_normal expects integers, so we multiply/divide for pseudo-float
            dt_phase_deviation = (GAMMA_RMS * ($dist_normal(req.get_inst_id(), 0, 1000) / 1000.0)) + GAMMA_DC;

            req.dt_jitter = dt_phase_deviation;
            req.v_tune    = 0.6;

            finish_item(req);
        end
    endtask

endclass

`endif // VCO_JITTER_SEQUENCE_SVH