#!/usr/bin/env python3
"""gen_verilog_a.py -- PPV to Verilog-A Behavioral Model Generator

Generates a native Verilog-A oscillator macro-model utilizing the extracted
Impulse Sensitivity Function (ISF/PPV) from the Python PPV suite. Uses the
idt() phase accumulator for proper frequency modulation tracking in
closed-loop PLL simulations.
"""

import json
import argparse
import sys
import os
import numpy as np


def main():
    parser = argparse.ArgumentParser(
        description="Generate Verilog-A oscillator model from PPV data")
    parser.add_argument("--input", type=str, required=True,
                        help="Input PPV JSON file (e.g., ppv_data.json)")
    parser.add_argument("--output", type=str, required=True,
                        help="Output Verilog-A file (e.g., oscillator.va)")
    parser.add_argument("--kvco", type=float, default=500e6,
                        help="VCO gain Kvco (Hz/V), default 500 MHz/V")
    args = parser.parse_args()

    if not os.path.exists(args.input):
        print(f"[ERROR] Could not find input file: {args.input}")
        sys.exit(1)

    print(f"[Verilog-A] Loading PPV data from {args.input}")
    with open(args.input, "r") as f:
        data = json.load(f)

    T0 = data.get("T0")
    if not T0:
        print("[ERROR] Input JSON does not contain T0 (period).")
        sys.exit(1)

    f0 = 1.0 / T0

    # Extract PPV arrays for all nodes
    nodes = data.get("nodes", {})
    if not nodes:
        print("[ERROR] Input JSON does not contain any node data.")
        sys.exit(1)

    target_node = "out_p" if "out_p" in nodes else list(nodes.keys())[0]
    ppv_array = nodes[target_node].get("ppv", [])

    if not ppv_array:
        print(f"[ERROR] Node '{target_node}' does not contain a PPV array.")
        sys.exit(1)

    # Compute Gamma_dc for flicker noise diagnostics
    ppv_clean = [p for p in ppv_array if p is not None]
    ppv_dc = np.mean(ppv_clean) if ppv_clean else 0
    ppv_rms = np.sqrt(np.mean(np.array(ppv_clean)**2)) if ppv_clean else 0
    dc_ratio = abs(ppv_dc) / (ppv_rms + 1e-30)

    if dc_ratio > 0.01:
        print(
            f"[WARNING] Gamma_dc/Gamma_rms = {dc_ratio:.4f} — high flicker noise upconversion susceptibility!")
    else:
        print(
            f"[INFO] Gamma_dc/Gamma_rms = {dc_ratio:.6f} — good flicker noise rejection.")

    num_phases = len(ppv_array)
    print(
        f"[Verilog-A] Extracting {num_phases} phase vectors for node {target_node}")

    va_template = f"""// Auto-generated Verilog-A Oscillator Macro-Model
// Extracted f0: {f0/1e9:.4f} GHz
// Base Node: {target_node}
// Gamma_dc/Gamma_rms: {dc_ratio:.6f}
// Generated by: PPV Solver Suite v2.0

`include "constants.vams"
`include "disciplines.vams"

module oscillator (out_p, out_n, vtune);
  electrical out_p, out_n, vtune;

  // Oscillator Properties
  parameter real f_nom = {f0:.6e};   // Nominal frequency (Hz)
  parameter real T0 = {T0:.6e};      // Nominal period (s)
  parameter real amp = 1.2;          // Output swing amplitude (V)
  parameter real Kvco = {args.kvco:.6e}; // VCO gain (Hz/V)
  parameter real v_tune_nom = 0.6;   // Nominal tuning voltage (V)

  // PPV phase sensitivity vector ({num_phases} phases)
  real ppv[{num_phases}];

  // State Variables
  real freq_inst;      // Instantaneous frequency
  real phase_inst;     // Integrated phase (via idt)
  real current_phase;  // Normalized phase [0, 1)
  integer phase_index; // Index into PPV array
  real noise_val;      // Random noise sample
  real phase_noise;    // Weighted phase noise contribution

  analog begin
    @(initial_step) begin
"""
    # Inject PPV array values
    for i, val in enumerate(ppv_array):
        if val is None:
            val = 0.0
        va_template += f"      ppv[{i}] = {val:.6e};\n"

    va_template += f"""    end

    // 1. Calculate instantaneous frequency based on Vtune
    //    This properly tracks frequency modulation in closed-loop PLLs
    freq_inst = f_nom + Kvco * (V(vtune) - v_tune_nom);

    // 2. Integrate frequency to get continuous phase (idt accumulator)
    //    This guarantees phase continuity even with variable step sizes
    phase_inst = 2 * `M_PI * idt(freq_inst, 0);

    // 3. Map integrated phase to normalized [0, 1) for PPV lookup
    current_phase = phase_inst / (2 * `M_PI);
    current_phase = current_phase - floor(current_phase);

    // 4. Map to nearest extracted PPV array index
    phase_index = $rtoi(current_phase * {num_phases});
    if (phase_index >= {num_phases}) phase_index = {num_phases} - 1;
    if (phase_index < 0) phase_index = 0;

    // 5. Modulate jitter using cyclostationary phase sensitivity
    noise_val = $random() % 1000 / 1000.0;
    phase_noise = noise_val * 1.0e-15 * ppv[phase_index];

    // 6. Output differential signal with integrated phase noise
    V(out_p, out_n) <+ amp * sin(phase_inst + phase_noise);
  end
endmodule
"""

    with open(args.output, "w") as f:
        f.write(va_template)

    print(
        f"[Verilog-A] Successfully generated behavioral model: {args.output}")
    print(f"[Verilog-A] Model uses idt() phase accumulator for PLL-safe frequency tracking.")


if __name__ == "__main__":
    main()
